service: sls-fieldney-bot
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: sa-east-1
  memorySize: 128
  timeout: 15
  environment:
      APP_ID: ${env:APP_ID}
      WEBHOOK_SECRET: ${env:WEBHOOK_SECRET}
      PRIVATE_KEY: ${env:PRIVATE_KEY}
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}
      OPENAI_ORG: ${env:OPENAI_ORG}
      SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
      SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
      INSTALLATION_ID: ${env:INSTALLATION_ID}
      GH_ORG_NAME: ${env:GH_ORG_NAME}
      TRELLO_API_TOKEN: ${env:TRELLO_API_TOKEN}
      TRELLO_API_KEY: ${env:TRELLO_API_KEY}
      TRELLO_SECRET: ${env:TRELLO_SECRET}
      ENVIRONMENT: ${opt:stage, 'dev'}
      AWS_REGION: ${env:AWS_REGION}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      LOG_FORMAT: json

functions:
  github:
    handler: index.github
    description: github fieldney-bot webhook

    events:
      - http:
          path: hooks/github
          method: post

  slack:
    handler: index.slack
    description: slack fieldney-bot webhook

    events:
      - http:
          path: hooks/slack
          method: post

  trello:
    handler: index.trello
    description: trello fieldney-bot webhook

    events:
      - http:
          path: hooks/trello
          method: any

plugins:
  - serverless-offline
  - serverless-offline-watcher

custom:
  serverless-offline-watcher:
    - path: 'src/'
      command: 'echo "app was modified, reloaded!"'
