service: sls-fieldney-bot
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: sa-east-1
  memorySize: 128
  timeout: 15

functions:
  index:
    handler: index.handler
    description: fieldney-bot webhook

    environment:
      APP_ID: ${env:APP_ID}
      WEBHOOK_SECRET: ${env:WEBHOOK_SECRET}
      PRIVATE_KEY: ${env:PRIVATE_KEY}
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}
      OPENAI_ORG: ${env:OPENAI_ORG}
      LOG_FORMAT: json

    events:
      - http:
          path: /probot
          method: post
