name: CI-CD fieldney-bot
on:
  push:
    branches: ['**']

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo's default branch
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install dependencies
        run: npm i

      - name: Create .env file
        run: |
          cat > .env << EOF
          ${{ secrets.ENV }}
          EOF

      - name: Run test
        run: npm test

      - name: deploy
        if: github.ref == 'refs/heads/master'
        run: |
          npx serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          npx serverless deploy --stage prod --verbose